/*
//  CreateObjectFormPageExamaobjectmodelPageNewFormView.java
//  
//
//  Generated by AnyPresence, Inc on 2014-12-19
//  Copyright (c) 2014 . All rights reserved.
 */

package com.anypresence.android.examplea;

import android.graphics.PorterDuff;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.view.View.OnClickListener;
import android.content.Intent;
import android.net.Uri;
import android.widget.*;
import android.app.Activity;
import android.view.ViewGroup.LayoutParams;

import android.support.v4.app.ListFragment;
import android.support.v4.app.Fragment;
import android.support.v4.view.MenuItemCompat;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Date;

import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.Map;
import java.util.HashMap;
import java.lang.ref.*;
import com.anypresence.library.*;

import com.anypresence.sdk.callbacks.*;
import com.anypresence.rails_droid.RemoteRequestException;
import com.anypresence.sdk.examplea.models.*;
import com.anypresence.sdk.acl.*;

public class CreateObjectFormPageExamaobjectmodelPageNewFormView
		extends
			AnyPresenceEditRoleFragment<com.anypresence.sdk.examplea.models.Examaobjectmodel> {

	private TextView createObjectFormPageExamaobjectmodelPageNewFormTextViewDateCreationDate0;

	private EditText createObjectFormPageExamaobjectmodelPageNewFormEditTextName1;

	private SimpleDateFormat dateFormat;
	private SimpleDateFormat timeFormat;

	public CreateObjectFormPageExamaobjectmodelPageNewFormView() {
		super();

	}

	/**
	 * Override this to change what the page looks like when a user is authorized to view it.
	 * There's also a createUnauthorizedView() method for when the user is not authorized.
	 * */
	@Override
	protected View createAuthorizedView() {
		final View root = View
				.inflate(
						getContext(),
						R.layout.create_object_form_page_examaobjectmodel_page_new_form,
						null);

		dateFormat = new SimpleDateFormat(APApplication.SIMPLE_DATE_FORMAT,
				getResources().getConfiguration().locale);
		timeFormat = new SimpleDateFormat(
				APApplication.SIMPLE_DATE_AND_TIME_FORMAT, getResources()
						.getConfiguration().locale);

		createObjectFormPageExamaobjectmodelPageNewFormTextViewDateCreationDate0 = (TextView) root
				.findViewById(R.id.create_object_form_page_examaobjectmodel_page_new_form_text_view_date_creation_date_0);
		if (getItem() != null) {
			if (getItem().getCreationDate() != null) {
				createObjectFormPageExamaobjectmodelPageNewFormTextViewDateCreationDate0
						.setText(dateFormat.format(getItem().getCreationDate()));
			}

			createObjectFormPageExamaobjectmodelPageNewFormTextViewDateCreationDate0
					.setOnClickListener(new View.OnClickListener() {
						@Override
						public void onClick(View view) {
							new DatePickerFragment(getItem().getCreationDate()) {
								@Override
								public void onDateSet(DatePicker view,
										int year, int month, int day) {
									TextView text = (TextView) root
											.findViewById(R.id.create_object_form_page_examaobjectmodel_page_new_form_text_view_date_creation_date_0);
									final Calendar cal = Calendar.getInstance();
									cal.set(Calendar.YEAR, year);
									cal.set(Calendar.MONTH, month);
									cal.set(Calendar.DAY_OF_MONTH, day);

									SimpleDateFormat df = new SimpleDateFormat(
											APApplication.SIMPLE_DATE_FORMAT,
											getResources().getConfiguration().locale);
									text.setText(df.format(cal.getTime()));
									if (getItem() != null) {
										getItem()
												.setCreationDate(cal.getTime());
									}
								}
							}.show(getFragmentManager(), "datePicker");
						}
					});
		}

		createObjectFormPageExamaobjectmodelPageNewFormEditTextName1 = (EditText) root
				.findViewById(R.id.create_object_form_page_examaobjectmodel_page_new_form_edit_text_name_1);
		if (getItem() != null && getItem().getName() != null) {
			createObjectFormPageExamaobjectmodelPageNewFormEditTextName1
					.setText(getItem().getName().toString());
		}

		// The scroll view should be set to match_parent and match_parent in the layout xml but, currently, it's not
		// behaving correctly.
		ScrollView createObjectFormPageExamaobjectmodelPageNewFormScrollView = (ScrollView) root
				.findViewById(R.id.create_object_form_page_examaobjectmodel_page_new_form_scroll_view);
		LayoutParams params = new LayoutParams(LayoutParams.MATCH_PARENT,
				LayoutParams.MATCH_PARENT);
		createObjectFormPageExamaobjectmodelPageNewFormScrollView
				.setLayoutParams(params);

		return root;
	}

	/**
	 * Called before save. Overwrite this method to do local form verification.
	 * */
	protected boolean saveVerification() {

		return true;
	}

	/**
	 * Called before save. Expectation is that any changes the user made in the
	 * form should be applied to the object now.
	 * */
	@Override
	public void updateItem(
			com.anypresence.sdk.examplea.models.Examaobjectmodel item) {

		item.setName(createObjectFormPageExamaobjectmodelPageNewFormEditTextName1
				.getText().toString());

	}

	@Override
	public void onPrepareOptionsMenu(Menu menu) {
		super.onPrepareOptionsMenu(menu);

		MenuItem save = menu.findItem(R.id.ap_save);
		if (save != null) {
			Drawable newIcon = save.getIcon();
			newIcon.mutate().setColorFilter(
					getResources().getColor(
							R.color.ap_custom_theme_title_font_color),
					PorterDuff.Mode.SRC_IN);
			save.setIcon(newIcon);
		}
	}

}
