/*
//  ListPageExamaobjectmodelsPageView.java
//  
//
//  Generated by AnyPresence, Inc on 2014-12-18
//  Copyright (c) 2014 . All rights reserved.
 */

package com.anypresence.android.examplea;

import android.support.v4.app.Fragment;
import android.support.v4.view.MenuItemCompat;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.view.LayoutInflater;
import android.widget.*;
import java.util.*;
import android.util.Log;

import com.anypresence.library.*;
import com.anypresence.sdk.callbacks.*;
import com.anypresence.sdk.cache.*;
import com.anypresence.sdk.cache.greendao.*;
import com.anypresence.rails_droid.RemoteRequestException;
import com.anypresence.rails_droid.ObjectId;
import com.anypresence.rails_droid.RemoteObject;
import java.lang.ref.*;
import android.net.Uri;
import android.content.Intent;

import com.anypresence.anypresence_inc.examplea.dao.APCachedRequestDao;
import com.anypresence.anypresence_inc.examplea.dao.APCachedRequest;

public class ListPageExamaobjectmodelsPageView
		extends
			AnyPresenceListFragment<com.anypresence.sdk.examplea.models.Examaobjectmodel> {
	private static final String TAG = ListPageExamaobjectmodelsPageView.class
			.getName();

	private static final int MENU_ITEM_PAGE_BUTTON = 0;

	public ListPageExamaobjectmodelsPageView() {
		super();

		setHasOptionsMenu(true);

		// Define the query for pulling data from the server
		setQueryScope("all");

	}

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		View root = View.inflate(getContext(),
				R.layout.list_page_examaobjectmodels_page, null);

		setHasOptionsMenu(true);

		return root;
	}

	@Override
	public void onResume() {
		super.onResume();

	}

	/**
	 * Override this to change what happens when a list item is clicked
	 * */
	@Override
	protected void onItemSelected(
			com.anypresence.sdk.examplea.models.Examaobjectmodel item) {
		super.onItemSelected(item);

		Bundle args = new Bundle();
		Fragment newInstance = new UpdateObjectFormPageExamaobjectmodelPageEditFormView();
		args.putSerializable("item", item);
		newInstance.setArguments(args);

		((ISimpleSwapFragmentListener) getActivity()).swapFragment(newInstance);

	}

	/**
	 * Override this to change what the list items look like
	 * */
	@Override
	protected AnyPresenceAdapter<com.anypresence.sdk.examplea.models.Examaobjectmodel> createAdapter(
			List<com.anypresence.sdk.examplea.models.Examaobjectmodel> items) {
		return new AnyPresenceAdapter<com.anypresence.sdk.examplea.models.Examaobjectmodel>(
				getContext(), items) {
			@Override
			public View inflateView() {

				return View.inflate(getContext(), R.layout.list_item, null);

			}

			@Override
			public void updateView(View convertView,
					com.anypresence.sdk.examplea.models.Examaobjectmodel object) {

				TextView titleView = (TextView) convertView
						.findViewById(R.id.title);
				TextView descriptionView = (TextView) convertView
						.findViewById(R.id.description);
				String title = getString(R.string.list_page_examaobjectmodels_page_text_view_detail_title);
				titleView.setText(Utility.interpolateText(object, title));
				String description = getString(R.string.list_page_examaobjectmodels_page_text_view_detail_description);
				descriptionView.setText(Utility.interpolateText(object,
						description));
				if (descriptionView.getText().toString().isEmpty()) {
					descriptionView.setVisibility(View.GONE);
				} else {
					descriptionView.setVisibility(View.VISIBLE);
				}

			}
		};
	}

	@Override
	public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
		super.onCreateOptionsMenu(menu, inflater);

		int existingMenuItemCount = menu.size();

		MenuItem pageButtonMenuItem = menu
				.add(Menu.NONE,
						MENU_ITEM_PAGE_BUTTON,
						existingMenuItemCount++,
						Utility.interpolateText(
								null,
								getResources()
										.getString(
												R.string.page_button_examaobjectmodel_page_new_button_button)));
		MenuItemCompat.setShowAsAction(pageButtonMenuItem,
				MenuItemCompat.SHOW_AS_ACTION_IF_ROOM);

	}
	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		getActivity().supportInvalidateOptionsMenu();

		switch (item.getItemId()) {

			case MENU_ITEM_PAGE_BUTTON :

				((ISimpleSwapFragmentListener) getActivity())
						.swapFragment(new CreateObjectFormPageExamaobjectmodelPageNewFormView());

				return true;

			default :
				return super.onOptionsItemSelected(item);
		}
	}

}
