/*
//  UpdateObjectFormPageExamaobjectmodelPageEditFormView.java
//  
//
//  Generated by AnyPresence, Inc on 2014-12-19
//  Copyright (c) 2014 . All rights reserved.
 */

package com.anypresence.android.examplea;

import android.graphics.PorterDuff;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.view.ViewGroup.LayoutParams;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Date;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import android.support.v4.view.MenuItemCompat;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

import com.anypresence.library.*;
import android.widget.*;
import android.util.Log;

public class UpdateObjectFormPageExamaobjectmodelPageEditFormView
		extends
			AnyPresenceEditRoleFragment<com.anypresence.sdk.examplea.models.Examaobjectmodel> {
	private static final String TAG = UpdateObjectFormPageExamaobjectmodelPageEditFormView.class
			.getName();

	private TextView updateObjectFormPageExamaobjectmodelPageEditFormTextViewDateCreationDate0;

	private EditText updateObjectFormPageExamaobjectmodelPageEditFormEditTextName1;

	private SimpleDateFormat dateFormat;
	private SimpleDateFormat timeFormat;

	public UpdateObjectFormPageExamaobjectmodelPageEditFormView() {
		super();

	}

	/**
	 * Override this to change what the page looks like when a user is authorized to view it.
	 * There's also a createUnauthorizedView() method for when the user is not authorized.
	 * */
	@Override
	protected View createAuthorizedView() {
		final View root = View
				.inflate(
						getContext(),
						R.layout.update_object_form_page_examaobjectmodel_page_edit_form,
						null);

		dateFormat = new SimpleDateFormat(APApplication.SIMPLE_DATE_FORMAT,
				getResources().getConfiguration().locale);
		timeFormat = new SimpleDateFormat(
				APApplication.SIMPLE_DATE_AND_TIME_FORMAT, getResources()
						.getConfiguration().locale);

		// Find some components and add listeners, etc.

		updateObjectFormPageExamaobjectmodelPageEditFormTextViewDateCreationDate0 = (TextView) root
				.findViewById(R.id.update_object_form_page_examaobjectmodel_page_edit_form_text_view_date_creation_date_0);
		if (getItem() != null) {
			if (getItem().getCreationDate() != null) {
				updateObjectFormPageExamaobjectmodelPageEditFormTextViewDateCreationDate0
						.setText(dateFormat.format(getItem().getCreationDate()));
			}

			updateObjectFormPageExamaobjectmodelPageEditFormTextViewDateCreationDate0
					.setOnClickListener(new View.OnClickListener() {
						@Override
						public void onClick(View view) {
							new DatePickerFragment(getItem().getCreationDate()) {
								@Override
								public void onDateSet(DatePicker view,
										int year, int month, int day) {
									TextView text = (TextView) root
											.findViewById(R.id.update_object_form_page_examaobjectmodel_page_edit_form_text_view_date_creation_date_0);
									final Calendar cal = Calendar.getInstance();
									cal.set(Calendar.YEAR, year);
									cal.set(Calendar.MONTH, month);
									cal.set(Calendar.DAY_OF_MONTH, day);

									SimpleDateFormat df = new SimpleDateFormat(
											APApplication.SIMPLE_DATE_FORMAT,
											getResources().getConfiguration().locale);
									text.setText(df.format(cal.getTime()));
									if (getItem() != null) {
										getItem()
												.setCreationDate(cal.getTime());
									}
								}
							}.show(getFragmentManager(), "datePicker");
						}
					});
		}

		updateObjectFormPageExamaobjectmodelPageEditFormEditTextName1 = (EditText) root
				.findViewById(R.id.update_object_form_page_examaobjectmodel_page_edit_form_edit_text_name_1);
		if (getItem() != null && getItem().getName() != null) {
			updateObjectFormPageExamaobjectmodelPageEditFormEditTextName1
					.setText(getItem().getName().toString());
		}

		// The scroll view should be set to match_parent and match_parent in the layout xml but, currently, it's not
		// behaving correctly.
		ScrollView updateObjectFormPageExamaobjectmodelPageEditFormScrollView = (ScrollView) root
				.findViewById(R.id.update_object_form_page_examaobjectmodel_page_edit_form_scroll_view);
		LayoutParams params = new LayoutParams(LayoutParams.MATCH_PARENT,
				LayoutParams.MATCH_PARENT);
		updateObjectFormPageExamaobjectmodelPageEditFormScrollView
				.setLayoutParams(params);

		return root;
	}

	/**
	 * Called before save. Overwrite this method to do local form verification.
	 * */
	protected boolean saveVerification() {

		return true;
	}

	/**
	 * Called before save. Expectation is that any changes the user made in the
	 * form should be applied to the object now.
	 * */
	@Override
	public void updateItem(
			com.anypresence.sdk.examplea.models.Examaobjectmodel item) {

		item.setName(updateObjectFormPageExamaobjectmodelPageEditFormEditTextName1
				.getText().toString());

	}

	@Override
	public void onPrepareOptionsMenu(Menu menu) {
		super.onPrepareOptionsMenu(menu);

		MenuItem save = menu.findItem(R.id.ap_save);
		if (save != null) {
			Drawable newIcon = save.getIcon();
			newIcon.mutate().setColorFilter(
					getResources().getColor(
							R.color.ap_custom_theme_title_font_color),
					PorterDuff.Mode.SRC_IN);
			save.setIcon(newIcon);
		}

		MenuItem delete = menu.findItem(R.id.ap_delete);
		if (delete != null) {
			Drawable newIcon = delete.getIcon();
			newIcon.mutate().setColorFilter(
					getResources().getColor(
							R.color.ap_custom_theme_title_font_color),
					PorterDuff.Mode.SRC_IN);
			delete.setIcon(newIcon);
		}
	}

}
